name: Generate code with ChatGPT
on:
  issues:
    types: [opened, reopened, labeled]
jobs:
  generate-code:
    env:
      GPT_SCRIPT: ./scripts/script.sh
      ISSUE_NUMBER: ${{ github.event.issue.number }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set permissions for script.sh
        run: ls -R;
          chmod +x $GPT_SCRIPT
      - name: Run script.sh
        run: echo "Run script.sh"; 
          $GPT_SCRIPT ${{ secrets.GITHUB_TOKEN }} $GITHUB_REPOSITORY $ISSUE_NUMBER ${{ secrets.OPENAI_API_KEY }}
      - name: Upload generated files as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-bot/
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: autocoder-artifact
          path: autocoder-artifact/
      - name: List files in the artifact
        run: ls -R autocoder-artifact/
